version: '3.8'

services:

  inventarioapi:
    depends_on: 
      - mysql
    build:
      context: ./Inventarioapi   
      dockerfile: dockerfile     
    ports:
      - "80:80"                  
    restart: unless-stopped      
    networks:
      - inventario_network

  inventariofront:
    build:
      context: ./inventariofront  
      dockerfile: dockerfile        
    ports:
      - "3000:3000"                 
    restart: unless-stopped      
    networks:
      - inventario_network

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootalfajor
      MYSQL_DATABASE: inventario
      MYSQL_USER: alfajor
      MYSQL_PASSWORD: alfajor
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventario_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootalfajor
    networks:
      - inventario_network

networks:
  inventario_network:
    driver: bridge

volumes:
  mysql_data:
